client_config_backend: file
client_config_file: client_secrets.json

save_credentials_backend: file
save_credentials_file: credentials.json
save_credentials: true

auth_method: service

oauth_scope:
  - https://www.googleapis.com/auth/drive
